---
- hosts: all
  sudo: true

  tasks:

    - name: install a few necessary packages
      action: apt pkg="{{ item }}" state=installed
      with_items:
        - make

    - name: download Python 1.2
      get_url: url='http://legacy.python.org/download/releases/src/python-1.2.tar.gz' dest=/etc/ mode=0440

    - name: unarchive Python source
      unarchive: src=/etc/python-1.2.tar.gz dest=/etc/ copy=no

    # make fails with gcc complaining that the function `getline` is defined
    # twice (with incompatible declarations).  Indeed, the Python 1.2 source
    # code has a function named `getline`.  stdio.h getline predates Python,
    # so it's odd that this ever worked, but whatever.  Let's rename the
    # Python-specific function to something else (_get_line)
    - name: "Fix a few source code warts so Python will compile with modern gcc"
      replace: dest="/etc/Python-1.2/Objects/fileobject.c" regexp="{{ item.before }}" replace="{{ item.after }}"
      with_items:
        - { before: 'getline', after: '_get_line' }
        - { before: 'file_get_line', after: 'filegetline' }

    - name: Install Python 1.2
      shell: "{{ item }}"
      args:
        chdir: "/etc/Python-1.2/"
      with_items:
        - "LIBS='-lm -lcrypt' ./configure --prefix=/usr/local"
        - make
        - make install
